# Generated by Django 5.2.1 on 2025-05-27 08:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('report_pdf', models.FileField(blank=True, null=True, upload_to='reports/')),
            ],
        ),
        migrations.CreateModel(
            name='Cheque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cheque_uploads/')),
                ('extracted_amt', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('date_str', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('accepted', 'Accepted'), ('discarded', 'Discarded'), ('flagged', 'Flagged')], default='flagged', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('image_hash', models.CharField(blank=True, max_length=64)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cheques', to='cheques.uploadsession')),
            ],
        ),
    ]
