# Generated by Django 5.2.1 on 2025-05-27 10:15

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='customer_name',
            field=models.CharField(default='Ram', max_length=255),
        ),
        migrations.AddField(
            model_name='uploadsession',
            name='customer_name',
            field=models.CharField(default='Ram', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadsession',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
