# Generated by Django 5.2.1 on 2025-05-27 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0002_cheque_customer_name_uploadsession_customer_name_and_more'),
        ('cheques', '0003_populate_customer_names'),
    ]

    operations = [
    ]
