# Generated by Django 5.2.1 on 2025-05-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0004_merge_20250527_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cheque',
            name='customer_name',
            field=models.CharField(max_length=255),
        ),
    ]
