# Generated by Django 5.2.1 on 2025-05-27 13:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0005_alter_cheque_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cheque',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
