# Generated by Django 5.2.1 on 2025-06-01 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cheques', '0006_cheque_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cheque',
            name='date_str',
        ),
    ]
